### ISSUE TITLE
travis 배포 실패 오류 p.355

### ISSUE THREAD

**Issue by bongdong2** [jojoldu/freelec-springboot2-webservice#182]
소스 커밋 후 travis > job log에 발생한 에러입니다. 
해당 에러 발생시 어떻게 해결해야 할 지 몰라 질문드립니다.

```log
/home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-s3-1.10.14/lib/dpl/provider/s3.rb:71:in `chdir': No such file or directory @ dir_chdir - deploy (Errno::ENOENT)
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-s3-1.10.14/lib/dpl/provider/s3.rb:71:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-1.10.14/lib/dpl/provider.rb:199:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-1.10.14/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-1.10.14/lib/dpl/provider.rb:199:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-s3-1.10.14/lib/dpl/provider/s3.rb:124:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-1.10.14/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-1.10.14/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-1.10.14/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.9/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.9/bin/dpl:23:in `<main>'
failed to deploy
```

.travis.yml
```yml
language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-webservice *
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo setting에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo setting에 설정된 값
    bucket: webservice-build # s3 버킷
    region: ap-northeast-2
    cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo setting에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo setting에 설정된 값
    bucket: webservice-build # s3 버킷
    key: springboot-webservice.zip # 빌드 파일을 압축해서 전달
    bundle_type : zip
    application : springboot-webservice # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: deployment-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
```
appspec.yml
```yml
version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes
```
